import PageShell from '@/components/page-shell';
import StorySections from '@/components/story-sections';
import RelatedLinks from '@/components/related-links';
export const metadata={title:'Who We Are'};
export default function About(){return <PageShell><header className="editorial-heading"><p className="eyebrow">Ness Sport Global</p><h1 className="red-text">Sport is our world.<br/>People are at its heart.</h1><p className="lead-copy">We manage players, work with teams and bring sporting events to life. Ness Sport Global connects these different parts of the game through one organisation.</p></header><section className="about-numbers" data-reveal><div><strong>08</strong><span>Players in our roster</span></div><div><strong>06</strong><span>Countries represented</span></div><div><strong>01</strong><span>Championship team campaign</span></div></section><StorySections sections={[
{title:'A connected view of sport.',paragraphs:['Sport is made up of individual stories and shared experiences. A player’s career, a team’s season and a live event each have their own demands, but they are closely connected.','NSG works across those connections. Our activity includes player management, team management and event organisation, with cricket at the centre of much of our work and international football tours expanding the picture.']},
{title:'People before profiles.',paragraphs:['Our roster includes William Bosisto, Priyank Panchal, Binod Bhandari, Gulshan Jha, Najibullah Zadran, GianPiero Meade, Adithya Shetty and Jay Gohel. They bring different roles and different experiences from across six countries.','We recognise those individual backgrounds. A career is shaped by more than one result: it is a continuing story of experience, decisions and the environments in which a player develops.']},
{title:'A team story in Sweden.',paragraphs:['In June 2026, NSG managed Vasteras United in the first Nordic Smash T20 Cricket League. The team finished the inaugural season as champions.','That campaign is part of our work with the collective side of sport — where a group of individuals comes together under one team identity.']},
{title:'What comes next.',paragraphs:['Our upcoming event plans include the Vini Jr India Tour on 4–5 October 2026 and the NSG Unity Cup from 10–17 October. Through NSG Talents and NSG Next, we also work in talent management.','These projects reflect the range of our interests: the individual, the team and the occasion that brings people together.']}
]}/><RelatedLinks title="Get to know our world." links={[{label:'Meet our players',href:'/players/'},{label:'Explore our work',href:'/work/'}]}/></PageShell>;}
