export type StorySection = { title: string; paragraphs: string[]; logo?: string };
export type PlayerStory = { role: string; headline: string; intro: string; paragraphs: string[]; facts: { label: string; value: string }[]; sources: { label: string; url: string }[] };
export const playerStories: Record<string, PlayerStory> = {
  'william-bosisto': {
    role: 'Batter · Off spin', headline: 'Australian grounding. International perspective.',
    intro: 'A right-handed batter from Western Australia, William Bosisto combines top-order experience with right-arm off spin and a background in leadership.',
    paragraphs: ['Bosisto captained Australia at the 2012 ICC Under-19 Cricket World Cup. That early responsibility was followed by a career in Australian domestic cricket, including a maiden Sheffield Shield century against Victoria at the Melbourne Cricket Ground in 2015.', 'He went on to captain the Cricket Australia XI in the 2016 Matador Cup. His cricket story brings together the demands of batting, the adaptability of a second discipline and the perspective gained from leading a side.', 'As part of the NSG roster, William represents the Australian dimension of a player group connected across several cricketing countries.'],
    facts: [{label:'Country',value:'Australia'},{label:'Batting',value:'Right-handed'},{label:'Bowling',value:'Right-arm off spin'},{label:'Career milestone',value:'Australia U19 captain, 2012'}],
    sources: [{label:'Cricket Australia profile',url:'https://www.cricket.com.au/players/CA%3A1051/will-bosisto'},{label:'ICC — Australia U19 captain',url:'https://www.icc-cricket.com/news/meet-will-bosisto-australia-skipper'}],
  },
  'priyank-panchal': {
    role: 'Opening batter', headline: 'A career built on patience and big innings.',
    intro: 'Priyank Panchal is a former Gujarat and India A captain whose career reflects the discipline and endurance of Indian first-class cricket.',
    paragraphs: ['A right-handed opening batter, Panchal became a central figure in Gujarat’s batting line-up. His unbeaten 314 against Punjab made him the first player to score a Ranji Trophy triple century for Gujarat.', 'His 2016–17 campaign produced 1,310 runs as Gujarat won its maiden Ranji Trophy title. Alongside his domestic achievements, he also captained India A, gaining experience in a leadership role beyond state cricket.', 'Panchal announced his retirement in May 2025 after a professional career spanning more than 17 years. He remains part of the talent roster managed by Ness Sport Global, bringing the perspective of a long career at the demanding end of domestic cricket.'],
    facts: [{label:'Country',value:'India'},{label:'Batting',value:'Right-handed'},{label:'Domestic team',value:'Gujarat'},{label:'Career milestone',value:'314* against Punjab'}],
    sources: [{label:'BCCI — Gujarat triple century',url:'https://www.bcci.tv/articles/2021/news/99285/Priyank-Panchal-becomes-first-Gujarat-player-to-slam-triple-century'},{label:'ESPNcricinfo — career retrospective',url:'https://www.espn.in/cricket/story/_/id/45328542/priyank-panchal-retires-all-forms-cricket'}],
  },
  'binod-bhandari': {
    role: 'Wicketkeeper-batter', headline: 'Experience at the heart of the game.',
    intro: 'Binod Bhandari is a Nepalese wicketkeeper and right-handed batter with a long association with Nepal’s national team.',
    paragraphs: ['Bhandari has been part of Nepal’s international cricket story since 2009. His role combines two different demands: the concentration required behind the stumps and the judgement needed with the bat.', 'A wicketkeeper sees every delivery from a unique position. That role brings responsibility for chances, communication and the rhythm of the fielding side, while batting adds a further contribution to the team.', 'Binod is one of the Nepalese players managed by NSG. Alongside Gulshan Jha, his place in the roster reflects our connection with Nepal’s cricket community and its presence in the wider game.'],
    facts: [{label:'Country',value:'Nepal'},{label:'Role',value:'Wicketkeeper-batter'},{label:'Batting',value:'Right-handed'},{label:'International background',value:'Nepal since 2009'}],
    sources: [{label:'ICC player profile',url:'https://www.icc-cricket.com/rankings/64408/binod-bhandari'},{label:'Cricbuzz career profile',url:'https://www.cricbuzz.com/profiles/9961/binod-bhandari-wk'}],
  },
  'gulshan-jha': {
    role: 'Seam-bowling all-rounder', headline: 'Two disciplines. One growing presence.',
    intro: 'Gulshan Jha brings left-handed batting and right-arm seam bowling to Nepal’s international game.',
    paragraphs: ['Jha made his ODI debut against the United States in September 2021. A young arrival on the international stage, he developed into an all-round option for Nepal in white-ball cricket.', 'In the 2023 ACC Men’s Premier Cup final, his unbeaten half-century helped Nepal qualify for the Asia Cup. In September 2024, he also became the first Nepalese player to combine a half-century with a five-wicket haul in the same ODI.', 'His role connects the batting and bowling sides of a team’s plan. As a member of the NSG roster, Gulshan adds an all-round profile to a group spanning established and emerging cricketing nations.'],
    facts: [{label:'Country',value:'Nepal'},{label:'Batting',value:'Left-handed'},{label:'Bowling',value:'Right-arm medium'},{label:'ODI debut',value:'September 2021'}],
    sources: [{label:'Cricket Association of Nepal',url:'https://cricketnepal.org.np/players/gulshan-jha/'},{label:'NDTV player biography',url:'https://sports.ndtv.com/cricket/players/114083-gulshan-jha-playerprofile'}],
  },
  'najibullah-zadran': {
    role: 'Middle-order batter', headline: 'Left-handed intent. Afghan experience.',
    intro: 'Najibullah Zadran is an Afghanistan international whose left-handed batting has been part of the country’s white-ball cricket journey.',
    paragraphs: ['Zadran’s international career began in 2012. He has featured in Afghanistan’s middle order, a role that asks a batter to read the match situation and respond as an innings develops.', 'His selection for the 2023 Asia Cup reflected the experience he brought to Afghanistan’s batting group. By that squad announcement, he had passed 2,000 runs in ODI cricket.', 'Najibullah brings an experienced Afghan perspective to the NSG roster. His profile sits alongside players from across South Asia, Australia, Europe and the Gulf, reflecting the international reach of our player management work.'],
    facts: [{label:'Country',value:'Afghanistan'},{label:'Role',value:'Batter'},{label:'Batting',value:'Left-handed'},{label:'International debut',value:'2012'}],
    sources: [{label:'ICC player profile',url:'https://www.icc-cricket.com/rankings/57991/najibullah-zadran'},{label:'ICC — 2023 Asia Cup squad',url:'https://www.icc-cricket.com/news/afghanistan-bank-on-experience-as-they-name-asia-cup-squad'}],
  },
  'gianpiero-meade': {
    role: 'Wicketkeeper-batter', headline: 'Part of Italy’s cricket story.',
    intro: 'GianPiero Meade is an Italian international wicketkeeper-batter, bringing a European dimension to the Ness Sport Global roster.',
    paragraphs: ['A right-handed batter, Meade has represented Italy in international cricket and was named in the country’s squad for its first ICC Men’s T20 World Cup campaign in 2026.', 'That selection placed him within a landmark chapter for Italian cricket. Italy reached the tournament following its successful European qualification campaign, taking the team onto a new global stage.', 'Meade’s wicketkeeping role combines close attention to each delivery with a contribution in the batting order. His presence in the NSG group reflects a cricket landscape that extends well beyond the game’s traditional centres.'],
    facts: [{label:'Country',value:'Italy'},{label:'Role',value:'Wicketkeeper-batter'},{label:'Batting',value:'Right-handed'},{label:'Career milestone',value:'Italy’s 2026 T20 World Cup squad'}],
    sources: [{label:'ICC — Italy World Cup squad',url:'https://www.icc-cricket.com/tournaments/mens-t20-world-cup-2026/news/italy-name-squad-for-maiden-men-s-t20-world-cup-campaign'},{label:'Cricbuzz player profile',url:'https://www.cricbuzz.com/profiles/15055/gian-piero-meade'}],
  },
  'adithya-shetty': {
    role: 'Leg-spin bowler', headline: 'A different angle on the game.',
    intro: 'Adithya Shetty is a right-arm leg-spin bowler associated with the United Arab Emirates national team.',
    paragraphs: ['Shetty’s route through UAE cricket included a scholarship at the ICC Academy in 2017 and a senior squad call-up while still a teenager. He made his ODI debut against West Indies in June 2023.', 'Leg spin brings a distinct discipline to a bowling attack. It asks for control, variation and the willingness to create chances, adding a different challenge for the batting side.', 'Adithya is the UAE player in the NSG roster. His cricket background connects our player group with the Gulf, alongside our representation of talent from Australia, South Asia and Europe.'],
    facts: [{label:'Country',value:'United Arab Emirates'},{label:'Role',value:'Bowler'},{label:'Bowling',value:'Right-arm leg spin'},{label:'ODI debut',value:'June 2023 · West Indies'}],
    sources: [{label:'Player background',url:'https://en.wikipedia.org/wiki/Adhitya_Shetty'},{label:'Gulf News — UAE’s young players',url:'https://gulfnews.com/amp/story/sport%2Fcricket%2Ficc%2Fhome-grown-talents-ready-to-carry-uae-cricket-team-on-their-young-shoulders-1.90767462'}],
  },
  'jay-gohel': {
    role: 'Cricket talent', headline: 'Regional roots. A wider cricket horizon.',
    intro: 'Jay Gohel is part of the Ness Sport Global cricket roster, with roots in Saurashtra, India.',
    paragraphs: ['Jay’s inclusion adds a connection to Saurashtra within NSG’s player group. Regional cricket is an essential part of the sport’s wider landscape: it is where players build their experience, develop their identity and contribute to their teams.', 'At NSG, the individual remains at the centre of the roster. Each player arrives with a different background and a different relationship with the game, from regional cricket to international competition.', 'Jay is managed alongside talent from Australia, Nepal, Afghanistan, Italy, the UAE and India. Together, the group reflects our focus on cricket across borders while recognising the places and communities each player comes from.'],
    facts: [{label:'Country',value:'India'},{label:'Region',value:'Saurashtra'},{label:'Sport',value:'Cricket'},{label:'Management',value:'Ness Sport Global'}], sources: [],
  },
};

export const workStories: Record<string, StorySection[]> = {
  'vasteras-united': [
    { title: 'A team at the start of something new.', paragraphs: ['The inaugural Nordic Smash T20 Cricket League brought a new competition to Sweden in June 2026. For Vasteras United, it was the beginning of a team story in that league — and the opportunity to set the standard in its first season.', 'Ness Sport Global managed Vasteras United throughout the campaign. Our involvement placed team management at the centre of a live competition, connecting the organisation’s work with the realities of tournament cricket.'] },
    { title: 'The first title belongs to United.', paragraphs: ['Vasteras United finished the first season as champions. That outcome makes the campaign a defining entry in NSG’s work: a team we managed, a new tournament and a championship in Sweden.', 'The photographs from the season capture different sides of that journey — the squad together, the action on the field and the celebration with the trophy. They tell the story of a competition that ended with United on top.'] },
    { title: 'Part of a wider cricket ambition.', paragraphs: ['Our work with Vasteras United sits alongside our management of individual players and our plans for the NSG Unity Cup. Together, these projects connect the people who play the game with the teams and events that give it a stage.'] },
  ],
  'vini-jr-india-tour': [
    { title: 'A football name. An Indian stage.', paragraphs: ['The Vini Jr India Tour is planned for 4 and 5 October 2026. NSG is bringing Vini Jr to India as part of its work in international sporting events.', 'The project takes our event activity beyond cricket. It brings together an international football personality and an Indian audience through a tour built around his visit.'] },
    { title: 'Two dates to look ahead to.', paragraphs: ['The announced tour window covers two days. It is the central planning detail available at this stage, with the programme and locations still to be announced.', 'Specific appearances, access arrangements and any ticket information will be shared when confirmed. The dates identify the planned tour window and do not yet represent a public schedule of individual activities.'] },
    { title: 'NSG beyond the boundary.', paragraphs: ['Alongside player management and team cricket, international tours are another part of the NSG story. This project reflects our interest in the shared space between sporting talent, live experiences and the audiences who follow them.'] },
  ],
  'nsg-unity-cup': [
    { title: 'Different teams. A shared stage.', paragraphs: ['The NSG Unity Cup is planned as a T20 cricket event from 10 to 17 October 2026. Its name reflects a simple ambition: bringing different teams together around a shared game.', 'The planned field includes Revo Music, a Saint Vincent and the Grenadines Cricket Association team, Scotland A and Portugal. The line-up gives the event an international character, with each team bringing its own cricketing context.'] },
    { title: 'The twenty-over format.', paragraphs: ['T20 cricket gives each side a maximum of twenty overs in a completed innings. Batting intent, bowling variation and fielding all play a part in a format where the match can change quickly.', 'For the Unity Cup, that format provides the foundation for a focused week of competition. The detailed match schedule, venue and competition arrangements will be announced as planning progresses.'] },
    { title: 'Built around participation.', paragraphs: ['The Unity Cup sits within NSG’s event-organising work and alongside its management of players and teams. It brings those interests together around a tournament rather than a single individual or club.', 'Further announcements will clarify match dates, team details and spectator information. Until then, the event overview sets out the planned window, format and participating teams.'] },
  ],
};

export const expertise = [
  { slug:'talent', label:'For Talent', title:'Every career has its own story.', intro:'We work with the people at the centre of sport. Ness Sport Global brings player management and talent management together under one organisation.', sections:[
    {title:'The player comes first.',paragraphs:['Our cricket roster includes eight players with backgrounds across six countries. It brings together different roles, stages of experience and routes into the game — from regional cricket to international competition.','A shared roster does not mean a shared career path. Our approach starts with recognising the individual: where they come from, the game they play and the direction of their next chapter.']},
    {title:'Connected to the wider game.',paragraphs:['Our work with talent sits alongside our involvement in teams and events. The Vasteras United campaign, international tour plans and the NSG Unity Cup make those connections visible across the organisation.','This wider perspective informs how we think about talent: as people within a changing sporting landscape, with a story that continues beyond a single match or competition.']},
    {title:'NSG Talents. NSG Next.',logo:'nsg-next.webp',paragraphs:['NSG Talents is our talent-management area, with NSG Next forming part of that offering. It sits alongside the sports roster within Ness Sport Global.']},
  ], links:[{label:'Meet our players',href:'/players/'},{label:'Explore NSG Next',href:'/nsg-next/'}] },
  { slug:'sports-talent', label:'Sports Talent', title:'Individual ability. A global game.', intro:'Our sports-talent work begins with cricket and the players we manage across Australia, India, Nepal, Afghanistan, Italy and the United Arab Emirates.', sections:[
    {title:'Different roles. Shared commitment.',paragraphs:['The NSG roster includes batters, wicketkeepers, spin bowlers and all-rounders. Each discipline contributes something different to the balance of a side, and each player brings a distinct background to the group.','We present those differences through individual profiles, recognising the player’s cricket identity rather than reducing a career to a single number or result.']},
    {title:'A roster without one border.',paragraphs:['Cricket is played through national teams, regional systems, clubs and leagues. Our player group reflects that variety, connecting established cricketing countries with nations building their presence in the game.','That breadth is part of our identity. We see value in the different environments that shape a player and the perspectives they bring when they come together.']},
    {title:'Part of Ness Sport Global.',paragraphs:['Player management is one part of NSG’s activity. Team management and event organisation complete the wider picture, bringing individual talent into the same conversation as clubs and competitions.']},
  ], links:[{label:'Explore the roster',href:'/players/'},{label:'Our team-management work',href:'/work/vasteras-united/'}] },
  { slug:'teams', label:'For Teams', title:'The individual matters. So does the team.', intro:'NSG’s work extends from the players on the field to the teams they are part of. Our team-management story includes Vasteras United’s championship campaign in Sweden.', sections:[
    {title:'One group. A common direction.',paragraphs:['Team sport asks individuals to contribute to something shared. Different roles, personalities and cricketing backgrounds come together in the same dressing room and on the same field.','Our interest in team management sits in that collective space: the team as an organisation, a sporting identity and a group competing together.']},
    {title:'Vasteras United, 2026.',paragraphs:['NSG managed Vasteras United during the first Nordic Smash T20 Cricket League, held in Sweden from 15 to 20 June 2026. The campaign ended with United as the inaugural champions.','It is a concrete example of our involvement in team cricket and a central project in the NSG portfolio. Explore the season story and photographs to see the team behind the result.']},
  ], links:[{label:'Vasteras United’s story',href:'/work/vasteras-united/'},{label:'About team management',href:'/expertise/team-management/'}] },
  { slug:'team-management', label:'Team Management', title:'Behind the name. Alongside the team.', intro:'Team management is a core part of Ness Sport Global’s work, connecting our focus on individual players with the wider demands of a competitive side.', sections:[
    {title:'A collective point of view.',paragraphs:['A team has its own identity, separate from any one player. It brings together the contributions of a squad within the setting of a league, season or tournament.','Our team-management work is part of the same sporting outlook that informs our player roster and events: people, teams and competitions are closely connected.']},
    {title:'A first-season success in Sweden.',paragraphs:['Vasteras United is the team NSG managed in the inaugural Nordic Smash T20 Cricket League. The tournament took place from 15 to 20 June 2026, and United finished as champions.','The campaign gives our team-management work a clear reference point. The club’s first-season title is documented through the squad and match photographs supplied for the project.']},
  ], links:[{label:'View the Vasteras United project',href:'/work/vasteras-united/'},{label:'Meet our players',href:'/players/'}] },
  { slug:'events', label:'For Events', title:'Sport brings people together.', intro:'From a cricket tournament to an international football tour, NSG organises sporting events that connect talent, teams and audiences.', sections:[
    {title:'Different formats. A shared purpose.',paragraphs:['Our event work includes team competition and personality-led tours. These are different experiences, united by the role sport plays in bringing people into the same moment.','The planned Vini Jr India Tour and NSG Unity Cup reflect that breadth: one centred on a football visit to India, the other on a field of cricket teams competing in the T20 format.']},
    {title:'October 2026.',paragraphs:['The Vini Jr India Tour is planned for 4–5 October, followed by the NSG Unity Cup from 10–17 October. Each event has its own overview page with the information currently available.','Detailed programmes, venues and spectator arrangements will be announced when confirmed. The event pages distinguish the planned dates from details that are still to come.']},
  ], links:[{label:'Vini Jr India Tour',href:'/work/vini-jr-india-tour/'},{label:'NSG Unity Cup',href:'/work/nsg-unity-cup/'}] },
  { slug:'tours', label:'International Tours', title:'Global talent. Local connection.', intro:'An international tour brings a sporting personality into a new setting. NSG’s upcoming tour project is the Vini Jr India Tour, planned for October 2026.', sections:[
    {title:'Taking sport beyond the match.',paragraphs:['The connection between a sporting figure and an audience extends beyond competition. A tour creates a different setting for that relationship, shaped by the place and the people involved.','Our tour work forms part of NSG’s broader event activity, alongside the teams and players we manage in cricket.']},
    {title:'Vini Jr in India.',paragraphs:['NSG is bringing Vini Jr to India for a planned visit on 4 and 5 October 2026. The project represents a football-focused addition to our sporting portfolio.','The tour’s programme and locations have not yet been announced. The dedicated event page will carry those details as they are confirmed.']},
  ], links:[{label:'Explore the India tour',href:'/work/vini-jr-india-tour/'},{label:'All NSG events',href:'/expertise/events/'}] },
  { slug:'cricket', label:'Cricket Events', title:'A shared game. New occasions.', intro:'Cricket connects the different parts of NSG: our players, our team-management work and the events we organise.', sections:[
    {title:'The game at the centre.',paragraphs:['Our cricket roster spans six countries, and our team portfolio includes the first-season Nordic Smash T20 champions, Vasteras United. Event organisation adds another dimension to those connections.','A tournament creates a shared occasion for teams with different backgrounds. It puts the focus on the game itself and the people who come together to play it.']},
    {title:'Introducing the NSG Unity Cup.',paragraphs:['Planned for 10–17 October 2026, the Unity Cup will use the T20 format. The planned teams are Revo Music, a Saint Vincent and the Grenadines Cricket Association team, Scotland A and Portugal.','The venue and match schedule are still to be announced. Visit the tournament overview for the planned field and the latest confirmed event details supplied by NSG.']},
  ], links:[{label:'Discover the Unity Cup',href:'/work/nsg-unity-cup/'},{label:'Meet our cricket talent',href:'/players/'}] },
];
